require 'pp'
require 'logger'
require 'net/ssh'

require_relative 'tidbits/lib/tidbits'
require_relative 'gitomate/config'
require_relative 'gitomate/yaml_log_format'
require_relative 'gitomate/cli_log_format'
require_relative 'gitomate/feedback'
require_relative 'gitomate/bare'
require_relative 'gitomate/bareSSH'
require_relative 'gitomate/repo'
require_relative 'gitomate/sync'
